"""
Single-qubit Clifford group for Gap-Scan RB.

The 24-element single-qubit Clifford group is generated by {H, S} and represented
here as 2x2 unitaries canonicalized up to global phase (i.e. elements of PSU(2)),
together with their SO(3) Bloch-sphere representation.

Why this module matters for the physics
---------------------------------------
The exact Clifford twirl of a Z-rotation is isotropic depolarizing:

    (1/24) sum_{C in Cliff_1} R(C)^-1 R_z(theta) R(C) = ((1 + 2 cos theta)/3) * I_3

Mechanism: the 24 Cliffords map Z to each of the 6 signed cardinal axes exactly
4 times. Averaging a rotation by theta over an axis and its negative symmetrizes
it to diag(cos theta, cos theta, 1); averaging that over the 3 axes gives
((1 + 2 cos theta)/3) I. `verify_twirl()` checks this to ~1e-16.

This identity is what makes the whole simulation tractable: it collapses the
Clifford average exactly, leaving only the *noise* average, which is where the
temporal correlation we study actually lives.

Units: dimensionless (no time enters this module).
"""
from __future__ import annotations

import numpy as np

__all__ = [
    "PAULIS",
    "clifford_unitaries",
    "clifford_unitaries_with_words",
    "clifford_words",
    "clifford_so3",
    "canonical_key",
    "compose_index_table",
    "inverse_index_table",
    "twirl_depolarizing_parameter",
    "verify_group",
    "verify_twirl",
]

# Pauli matrices (I, X, Y, Z)
PAULIS = (
    np.eye(2, dtype=complex),
    np.array([[0, 1], [1, 0]], dtype=complex),
    np.array([[0, -1j], [1j, 0]], dtype=complex),
    np.array([[1, 0], [0, -1]], dtype=complex),
)

_H = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
_S = np.array([[1, 0], [0, 1j]], dtype=complex)


def _so3_of(u: np.ndarray) -> np.ndarray:
    """Bloch/SO(3) representation of a 2x2 unitary: R_ij = (1/2) Tr(s_i U s_j U^dag)."""
    ud = u.conj().T
    r = np.empty((3, 3), dtype=float)
    for i in range(3):
        for j in range(3):
            r[i, j] = 0.5 * np.trace(PAULIS[i + 1] @ u @ PAULIS[j + 1] @ ud).real
    return r


def canonical_key(u: np.ndarray, decimals: int = 6) -> tuple:
    """Hashable key identifying a 2x2 unitary *up to global phase*.

    Keying on the SO(3) Bloch matrix rather than the raw entries makes this
    phase-invariant BY CONSTRUCTION: the adjoint action R_ij = (1/2)Tr(s_i U s_j U^dag)
    is unchanged by U -> e^{i phi} U, so no pivot entry has to be chosen.

    An earlier version normalized the largest-magnitude entry to positive real,
    which silently broke on matrices like H whose entries are all equal in
    magnitude: floating-point noise flipped which entry argmax selected between a
    matrix and its phase-rotated twin, so the same group element produced two
    different keys and the closure blew past 24 elements. For Cliffords the SO(3)
    entries are exactly 0/+1/-1 (signed permutation matrices), so rounding is safe.
    """
    return tuple(np.round(_so3_of(u).reshape(-1), decimals) + 0.0)


def clifford_unitaries_with_words() -> tuple[np.ndarray, list[list[str]]]:
    """Return the 24 Cliffords plus an exact generator word for each.

    Words are lists of 'h'/'s' in CIRCUIT order (leftmost applied first), so a hardware
    circuit can be emitted gate-by-gate with no unitary synthesis and hence no synthesis
    error. Note matrix order is the reverse of circuit order: matrix = g @ u corresponds
    to applying u first, then g.
    """
    ident = np.eye(2, dtype=complex)
    elements = [ident]
    words: list[list[str]] = [[]]
    seen = {canonical_key(ident)}
    frontier = [(ident, [])]
    while frontier:
        nxt = []
        for u, word in frontier:
            for g, name in ((_H, "h"), (_S, "s")):
                w = g @ u
                k = canonical_key(w)
                if k not in seen:
                    seen.add(k)
                    new_word = word + [name]      # circuit order: existing gates, then g
                    elements.append(w)
                    words.append(new_word)
                    nxt.append((w, new_word))
        frontier = nxt
    if len(elements) != 24:
        raise RuntimeError(f"Clifford closure produced {len(elements)} elements, expected 24")
    return np.array(elements), words


def clifford_words() -> list[list[str]]:
    """Generator words ('h'/'s', circuit order) for each of the 24 Cliffords."""
    return clifford_unitaries_with_words()[1]


def clifford_unitaries() -> np.ndarray:
    """Return the 24 single-qubit Cliffords as an array of shape (24, 2, 2).

    Built by breadth-first closure of the group generated by {H, S}. The
    identity is guaranteed to be element 0.
    """
    return clifford_unitaries_with_words()[0]


def clifford_so3(unitaries: np.ndarray | None = None) -> np.ndarray:
    """SO(3) Bloch representation of each Clifford: R_ij = (1/2) Tr(s_i U s_j U^dag).

    Returns shape (n, 3, 3), real.
    """
    if unitaries is None:
        unitaries = clifford_unitaries()
    return np.array([_so3_of(u) for u in unitaries])


def compose_index_table(unitaries: np.ndarray | None = None) -> np.ndarray:
    """Multiplication table: table[a, b] = index of (U_a @ U_b)."""
    if unitaries is None:
        unitaries = clifford_unitaries()
    lookup = {canonical_key(u): i for i, u in enumerate(unitaries)}
    n = len(unitaries)
    table = np.empty((n, n), dtype=np.int64)
    for a in range(n):
        for b in range(n):
            k = canonical_key(unitaries[a] @ unitaries[b])
            if k not in lookup:
                raise RuntimeError("group not closed under multiplication")
            table[a, b] = lookup[k]
    return table


def inverse_index_table(unitaries: np.ndarray | None = None) -> np.ndarray:
    """inv[a] = index of the inverse of U_a."""
    if unitaries is None:
        unitaries = clifford_unitaries()
    lookup = {canonical_key(u): i for i, u in enumerate(unitaries)}
    n = len(unitaries)
    inv = np.empty(n, dtype=np.int64)
    for a in range(n):
        k = canonical_key(unitaries[a].conj().T)
        if k not in lookup:
            raise RuntimeError("inverse not in group")
        inv[a] = lookup[k]
    return inv


def twirl_depolarizing_parameter(theta: float | np.ndarray) -> np.ndarray:
    """Exact Clifford-twirled Bloch contraction of Rz(theta): p = (1 + 2 cos theta)/3.

    WARNING (false-positive trap for the quantum-memory witness): p vanishes at
    |theta| = 2*pi/3 ~ 2.0944 and is NEGATIVE beyond it. Classical noise strong
    enough to reach |theta| > 2*pi/3 therefore produces sign-alternating,
    NON-monotonic ASF, which counterfeits the quantum-memory signature of
    arXiv:2510.13051. Keep phases well below 2*pi/3, or report the violation.
    """
    return (1.0 + 2.0 * np.cos(np.asarray(theta, dtype=float))) / 3.0


def verify_group(unitaries: np.ndarray | None = None) -> dict:
    """Check unitarity, closure, and inverse correctness. Returns a report dict."""
    if unitaries is None:
        unitaries = clifford_unitaries()
    n = len(unitaries)
    unitarity = max(
        float(np.max(np.abs(u.conj().T @ u - np.eye(2)))) for u in unitaries
    )
    table = compose_index_table(unitaries)
    inv = inverse_index_table(unitaries)
    # Each row/column of a group multiplication table is a permutation.
    rows_perm = all(len(set(table[a].tolist())) == n for a in range(n))
    cols_perm = all(len(set(table[:, b].tolist())) == n for b in range(n))
    inv_ok = all(table[a, inv[a]] == 0 and table[inv[a], a] == 0 for a in range(n))
    # SO(3) reps must be genuine rotations (det = +1, orthogonal).
    so3 = clifford_so3(unitaries)
    dets = np.array([np.linalg.det(r) for r in so3])
    orth = max(float(np.max(np.abs(r.T @ r - np.eye(3)))) for r in so3)
    # Z must map to each of the 6 signed cardinal axes exactly 4 times.
    z_images = [tuple(np.round(r[:, 2], 9) + 0.0) for r in so3]
    counts = {}
    for z in z_images:
        counts[z] = counts.get(z, 0) + 1
    return {
        "order": n,
        "max_unitarity_error": unitarity,
        "rows_are_permutations": rows_perm,
        "cols_are_permutations": cols_perm,
        "inverses_correct": inv_ok,
        "so3_orthogonality_error": orth,
        "so3_dets_all_plus_one": bool(np.allclose(dets, 1.0)),
        "distinct_z_images": len(counts),
        "z_image_multiplicities": sorted(counts.values()),
    }


def verify_twirl(thetas=(0.05, 0.3, 1.0, 2.0)) -> dict:
    """Verify the exact twirl identity against the analytic (1+2cos t)/3."""
    so3 = clifford_so3()
    out = {}
    for th in thetas:
        c, s = np.cos(th), np.sin(th)
        rz = np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])
        avg = np.zeros((3, 3))
        for r in so3:
            avg += r.T @ rz @ r
        avg /= len(so3)
        p_analytic = float(twirl_depolarizing_parameter(th))
        out[float(th)] = {
            "p_analytic": p_analytic,
            "max_dev_from_pI": float(np.max(np.abs(avg - p_analytic * np.eye(3)))),
        }
    return out


if __name__ == "__main__":
    print("=== Clifford group verification ===")
    rep = verify_group()
    for k, v in rep.items():
        print(f"  {k}: {v}")

    ok_group = (
        rep["order"] == 24
        and rep["max_unitarity_error"] < 1e-12
        and rep["rows_are_permutations"]
        and rep["cols_are_permutations"]
        and rep["inverses_correct"]
        and rep["so3_orthogonality_error"] < 1e-12
        and rep["so3_dets_all_plus_one"]
        and rep["distinct_z_images"] == 6
        and rep["z_image_multiplicities"] == [4, 4, 4, 4, 4, 4]
    )
    print(f"  -> group valid: {'PASS' if ok_group else 'FAIL'}")

    print("\n=== exact Clifford twirl -> isotropic depolarizing ===")
    tw = verify_twirl()
    worst = 0.0
    for th, d in tw.items():
        print(f"  theta={th:<5} p=(1+2cos t)/3={d['p_analytic']:.12f}  "
              f"max|avg - p*I|={d['max_dev_from_pI']:.3e}")
        worst = max(worst, d["max_dev_from_pI"])
    ok_twirl = worst < 1e-12
    print(f"  -> twirl identity exact: {'PASS' if ok_twirl else 'FAIL'} (worst {worst:.3e})")

    print("\n=== sign constraint (false-positive trap) ===")
    crit = 2 * np.pi / 3
    print(f"  p(2pi/3)      = {float(twirl_depolarizing_parameter(crit)):.3e}  (must be ~0)")
    print(f"  p(1.01*2pi/3) = {float(twirl_depolarizing_parameter(1.01 * crit)):.6f}  (must be < 0)")
    ok_sign = (
        abs(float(twirl_depolarizing_parameter(crit))) < 1e-12
        and float(twirl_depolarizing_parameter(1.01 * crit)) < 0
    )
    print(f"  -> sign behaviour as specified: {'PASS' if ok_sign else 'FAIL'}")

    all_ok = ok_group and ok_twirl and ok_sign
    print(f"\nclifford.py self-test: {'PASS' if all_ok else 'FAIL'}")
    raise SystemExit(0 if all_ok else 1)
