"""Prepare and verify local QST upload files; no submission or publication."""
from __future__ import annotations
import argparse
import csv
import hashlib
import io
import json
from pathlib import Path
import re
import shutil
from zipfile import ZipFile, ZIP_DEFLATED

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "submission"


def expanded_tex(path, visited=None):
    visited = set() if visited is None else visited
    path = path.resolve()
    if path in visited:
        raise ValueError("Cyclic or repeated TeX input")
    visited.add(path)
    body = path.read_text(encoding="utf-8")
    def replace(match):
        child = path.parent / match.group(1)
        if not child.suffix:
            child = child.with_suffix(".tex")
        return expanded_tex(child, visited)
    return re.sub(r"\\input\{([^}]+)\}", replace, body)


def prepare():
    OUT.mkdir(exist_ok=True)
    body = expanded_tex(ROOT / "paper/main.tex")
    if "aps,pra,twocolumn" not in body:
        raise ValueError("Unexpected source document class; review submission conversion")
    body = body.replace("aps,pra,twocolumn", "aps,pra,onecolumn,12pt")
    # REVTeX's default double-spaced front matter overfills the title page.
    # Keep the abstract at 12 pt with 15 pt leading; retain the body spacing.
    body = body.replace(r"\begin{abstract}",
                        r"\begin{abstract}" + "\n" + r"\linespread{1}\fontsize{12}{15}\selectfont")
    body = body.replace(r"\maketitle", r"\maketitle\clearpage")
    body = body.replace(r"width=\columnwidth", r"width=0.60\textwidth")
    target = ROOT / "paper/qst_submission.tex"
    target.write_text("% Generated by scripts/build_submission.py --prepare.\n"+body, encoding="utf-8")
    print("Prepared 12-point, one-column QST source:", target.relative_to(ROOT))


def export_tables():
    path = ROOT / "data/phase_cycle_observations.csv"
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(["job_id", "backend", "qubit", "execution_index", "arm", "block",
                         "setting", "calibration_state", "count_zero", "count_one", "shots"])
        for raw_path in sorted((ROOT / "data").glob("phase_cycle_*_counts.json")):
            raw = json.loads(raw_path.read_text(encoding="utf-8"))
            pending = json.loads((ROOT / raw["pending_file"].replace("\\", "/")).read_text(encoding="utf-8"))
            d = pending["design"]
            for i, (counts, mt) in enumerate(zip(raw["counts"], pending["execution_meta"], strict=True)):
                if set(counts)-{"0", "1"}:
                    raise ValueError("Unexpected measurement labels in phase-cycle counts")
                writer.writerow([raw["job_id"], d["backend"], d["qubit"], i,
                                 mt.get("arm", ""), mt.get("block", ""), mt.get("setting", ""),
                                 mt.get("calibration_state", ""), counts.get("0", 0),
                                 counts.get("1", 0), sum(counts.values())])
    comparison = json.loads((ROOT / "data/phase_cycle_review.json").read_text(encoding="utf-8"))["comparator"]
    with (ROOT / "data/phase_cycle_comparator.csv").open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(["model", "trial", "truth_sine_covariance", "rb_normalized_estimate", "ramsey_estimate"])
        for row in comparison["rows"]:
            for i, (rb, ramsey) in enumerate(row["estimates"]):
                writer.writerow([row["model"], i, row["truth"], rb, ramsey])


def category(path):
    name = path.name
    if name.startswith("gapscan_fake_"):
        return "simulator_preflight_not_hardware"
    if name.endswith("_counts.json") or name == "phase_cycle_observations.csv":
        return "observed_hardware_counts"
    if name.endswith("_failure.json"):
        return "failed_acquisition_no_counts"
    if "validation" in name or "comparator" in name or name == "threshold_calibration.json":
        return "simulation_or_simulation_validation"
    if name == "phase_cycle_review.json":
        return "simulation_checks_and_hardware_calibration_sensitivity"
    if "pending" in name or "design" in name:
        return "design_execution_metadata_not_measurement"
    if name.endswith("_results.json"):
        raw = path.with_name(name.replace("_results", "_counts"))
        return "derived_hardware_summary_with_raw_counts" if raw.exists() else "legacy_summary_only"
    if path.suffix == ".npz":
        return "legacy_survival_arrays_not_raw_bitstrings"
    if name == "sensitivity.json":
        return "historical_exclusion_interpretation_withdrawn"
    return "derived_analysis_metadata_or_audit"


def check_data_keys(value, path):
    sensitive = {"token", "apikey", "accesstoken", "refreshtoken", "password", "clientsecret", "authorization"}
    if isinstance(value, dict):
        for key, child in value.items():
            if re.sub(r"[^a-z]", "", key.lower()) in sensitive and child:
                raise ValueError(f"Credential-like field in {path}: {key}; inspect before packaging")
            check_data_keys(child, path)
    elif isinstance(value, list):
        for child in value:
            check_data_keys(child, path)


def write_zip(path, entries, kind):
    records = {name: dict(bytes=len(value), sha256=hashlib.sha256(value).hexdigest())
               for name, value in sorted(entries.items())}
    manifest = dict(kind=kind, publication_status="prepared_locally_not_submitted_or_published", files=records)
    with ZipFile(path, "w", ZIP_DEFLATED) as archive:
        for name, content in sorted(entries.items()):
            archive.writestr(name, content)
        archive.writestr("manifest.json", json.dumps(manifest, indent=2).encode())
    with ZipFile(path) as archive:
        assert archive.testzip() is None
        assert set(archive.namelist()) == set(entries) | {"manifest.json"}
        for name, record in records.items():
            assert hashlib.sha256(archive.read(name)).hexdigest() == record["sha256"]
    return dict(file=path.name, bytes=path.stat().st_size,
                sha256=hashlib.sha256(path.read_bytes()).hexdigest(), verified_files=len(records))


def package():
    source = ROOT / "paper/qst_submission.tex"
    pdf = ROOT / "paper/qst_submission.pdf"
    if not pdf.exists() or pdf.stat().st_mtime < source.stat().st_mtime:
        raise ValueError("Compile the prepared QST source before packaging")
    export_tables()
    selected = set()
    for folder in ("sim", "estimator", "hardware", "scripts"):
        selected.update((ROOT / folder).glob("*.py"))
    for pattern in ("*.json", "*.jsonl", "*.npz", "*.csv"):
        selected.update((ROOT / "data").glob(pattern))
    for name in ("requirements.txt", "requirements.lock.txt", "requirements-reproduce.txt", "sanity_check.py",
                 "LICENSE", "LICENSE_DATA.md", "ATTRIBUTION.md", "NOTICE", "CITATION.cff"):
        selected.add(ROOT / name)
    for name in ("main.tex", "numbers.tex", "phase_cycle_hardware.tex", "phase_cycle_review.tex",
                 "readout_sensitivity.tex", "refs.bib"):
        selected.add(ROOT / "paper" / name)
    for pattern in ("fig_*.pdf", "fig_*.png"):
        selected.update((ROOT / "figures").glob(pattern))
    for path in selected:
        if path.parent == ROOT / "data":
            if path.suffix == ".json":
                check_data_keys(json.loads(path.read_text(encoding="utf-8")), path.name)
            elif path.suffix == ".jsonl":
                for line in path.read_text(encoding="utf-8").splitlines():
                    if line.strip():
                        check_data_keys(json.loads(line), path.name)
    entries = {p.relative_to(ROOT).as_posix(): p.read_bytes() for p in sorted(selected)}
    entries["README.md"] = (OUT / "supplement_readme.md").read_bytes()
    inventory = io.StringIO(newline="")
    writer = csv.writer(inventory)
    writer.writerow(["file", "evidence_category", "bytes", "sha256"])
    for path in sorted(p for p in selected if p.parent == ROOT / "data"):
        writer.writerow([path.relative_to(ROOT).as_posix(), category(path), path.stat().st_size,
                         hashlib.sha256(path.read_bytes()).hexdigest()])
    entries["data_inventory.csv"] = inventory.getvalue().encode("utf-8")
    (OUT / "data_inventory.csv").write_bytes(entries["data_inventory.csv"])
    supp = write_zip(OUT / "supplementary_reproducibility.zip", entries, "supplementary_data_and_code")

    source_entries = {"paper/qst_submission.tex": source.read_bytes(),
                      "paper/refs.bib": (ROOT / "paper/refs.bib").read_bytes()}
    for graphic in re.findall(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", source.read_text(encoding="utf-8")):
        path = (source.parent / graphic).resolve()
        source_entries[path.relative_to(ROOT).as_posix()] = path.read_bytes()
    src = write_zip(OUT / "manuscript_source.zip", source_entries, "manuscript_source")
    shutil.copyfile(pdf, OUT / "manuscript.pdf")
    manuscript = dict(file="manuscript.pdf", bytes=pdf.stat().st_size,
                      sha256=hashlib.sha256(pdf.read_bytes()).hexdigest())
    assert supp["bytes"] < 50_000_000 and sum(r["bytes"] for r in (supp, src, manuscript)) < 150_000_000
    declarations = json.loads((OUT / "author_declarations.json").read_text(encoding="utf-8"))
    missing = [key for key in ("corresponding_author", "submitting_author", "funding_statement",
                               "competing_interests_statement", "not_under_consideration_elsewhere")
               if not declarations.get(key)]
    for author in declarations["authors"]:
        for key in ("contributions", "approved_final_version", "accepts_accountability"):
            if not author.get(key):
                missing.append(author["name"]+": "+key)
    if declarations.get("approved_manuscript_sha256") != manuscript["sha256"]:
        missing.append("all-author approval of the current manuscript SHA-256")
    if re.search(r"(?:statement|declaration) is pending", source.read_text(encoding="utf-8")):
        missing.append("replace pending manuscript declarations with confirmed facts")
    disclosure_path = OUT / "ai_disclosure.json"
    if disclosure_path.exists():
        disclosure = json.loads(disclosure_path.read_text(encoding="utf-8"))
        if (disclosure.get("publisher_requires_manuscript_acknowledgment")
                and not disclosure.get("included_in_manuscript")
                and not disclosure.get("editor_approved_metadata_only")):
            missing.append("resolve QST's manuscript AI-disclosure requirement; metadata-only placement has no recorded editorial exception")
    manifest = dict(target_journal="Quantum Science and Technology", article_type="Paper",
                    review_model="single-anonymous", access_route="subscription",
                    package_verified=True, ready_for_author_review=True, ready_to_submit=not missing,
                    not_submitted=True, public_archive_doi=None,
                    data_route="journal supplementary files; DOI assigned on publication",
                    files=[manuscript, supp, src], author_actions_pending=missing)
    (OUT / "package_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(json.dumps({k: manifest[k] for k in ("package_verified", "ready_to_submit", "files")}, indent=2))
    print("Author facts/version approval remain pending:", len(missing), "checks")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--prepare", action="store_true")
    group.add_argument("--package", action="store_true")
    args = ap.parse_args()
    if args.prepare:
        prepare()
    else:
        package()
