"""
Emit paper/numbers.tex: every number quoted in the manuscript, as a LaTeX macro read
straight from the archived data files.

The manuscript never hard-codes a measured value. That is not tidiness for its own sake --
a paper whose numbers are retyped by hand drifts from its dataset the moment a run is
repeated, and the drift is invisible until a referee recomputes something. Here a changed
JSON changes the macro, which changes the sentence, on the next build.

    .venv\\Scripts\\python.exe scripts\\make_numbers.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

DATA = Path("data")
OUT = Path("paper") / "numbers.tex"


def _latest(pattern):
    f = sorted(DATA.glob(pattern))
    return json.loads(f[-1].read_text(encoding="utf-8")) if f else None


def _fmt(x, nd=2):
    if x is None:
        return r"\text{n/a}"
    x = float(x)
    if x == 0:
        return "0"
    if 1e-2 <= abs(x) < 1e4:
        return f"{x:.{nd}f}"
    from math import floor, log10
    e = floor(log10(abs(x)))
    return rf"{x / 10**e:.{nd}f}\times 10^{{{e}}}"


def main():
    lines = [
        "% AUTO-GENERATED by scripts/make_numbers.py -- do not edit by hand.",
        "% Every macro below is read from the JSON files in data/.",
        "",
    ]

    def mac(name, value):
        lines.append(rf"\newcommand{{\{name}}}{{{value}\xspace}}")

    # ---- Hardware positive control ------------------------------------------------
    pos = _latest("poscontrol_*_main*_results.json")
    if pos:
        mac("posBackend", pos["backend"].replace("_", r"\_"))
        mac("posQubit", str(pos["qubit"]))
        mac("posNgaps", str(len(pos["delays_ns"])))
        mac("posGapMin", f"{min(pos['delays_ns']):.0f}")
        mac("posGapMax", f"{max(pos['delays_ns']):.0f}")
        for a in pos["arms"]:
            n = a["name"].capitalize()
            mac(f"nuPred{n}", _fmt(a["nu_predicted"]))
            mac(f"nuMeas{n}", _fmt(a["nu_measured"]))
            mac(f"nuErr{n}", _fmt(a["nu_stderr"]))
            mac(f"tauC{n}", _fmt(a["tau_c_s"] * 1e9, 1))
            if a.get("z_vs_prediction") is not None:
                mac(f"zScore{n}", _fmt(abs(a["z_vs_prediction"])))
            if a.get("w_var_rep") is not None:
                mac(f"wvarRep{n}", _fmt(a["w_var_rep"]))
        zs = [abs(a["z_vs_prediction"]) for a in pos["arms"]
              if a.get("z_vs_prediction") is not None]
        if zs:
            mac("posMaxZ", _fmt(max(zs)))

    # ---- Secondary witnesses, calibrated in the DD / repeated-sequence job ------------
    ddrep = _latest("poscontrol_*_ddrep_results.json")
    if ddrep:
        for a in ddrep.get("arms", []):
            if a.get("w_var_rep") is not None:
                mac(f"wvarRep{a['name'].capitalize()}DD", _fmt(a["w_var_rep"]))
            rows = sorted([r for r in a.get("dd", []) if r.get("ratio") is not None],
                          key=lambda r: r["delta_ns"])
            if len(rows) >= 2:
                mac("ddRatioLo", _fmt(rows[0]["ratio"]))
                mac("ddRatioHi", _fmt(rows[-1]["ratio"]))
                mac("ddHeadroomLo", _fmt(rows[0]["headroom"], 0))
                mac("ddHeadroomHi", _fmt(rows[-1]["headroom"], 0))
                mac("ddGapLo", f"{rows[0]['delta_ns']:.0f}")
                mac("ddGapHi", f"{rows[-1]['delta_ns']:.0f}")

    # ---- ROC calibration of the decision threshold -----------------------------------
    roc = _latest("threshold_calibration.json")
    if roc:
        mac("rocTrials", str(roc["trials_per_class"]))
        mac("rocChosen", _fmt(roc["chosen_threshold"]))
        mac("rocTpr", _fmt(roc["tpr_at_chosen"]))
        mac("rocFpr", _fmt(roc["fpr_at_chosen"]))
        if roc.get("fpr_upper95_at_chosen") is not None:
            mac("rocFprUpper", _fmt(roc["fpr_upper95_at_chosen"]))
        tcs = roc.get("positive_tau_c_us") or []
        if tcs:
            mac("rocTauMin", _fmt(min(tcs), 0))
            mac("rocTauMax", _fmt(max(tcs), 0))
        from estimator.witness import NU_MARKOVIAN_MAX
        mac("rocShipped", _fmt(NU_MARKOVIAN_MAX))
        if roc.get("plateau_lo") is not None:
            mac("rocPlateauLo", _fmt(roc["plateau_lo"]))
            mac("rocPlateauHi", _fmt(roc["plateau_hi"]))

    # ---- Null survey and exclusion --------------------------------------------------
    sens = _latest("sensitivity.json")
    if sens:
        mac("nullNu", _fmt(sens["nu"]))
        mac("nullNuErr", _fmt(sens["nu_stderr"]))
        mac("nullQubit", str(sens["qubit"]))
        # The former 25% macro silently generalized the best point to the whole
        # tau range and ignored model adequacy. Do not regenerate that claim.

    audit = _latest("sensitivity_profile_audit.json")
    if audit:
        mac("auditChiMin", _fmt(min(r["minimum_chi2"] for r in audit["rows"])))
        mac("auditChiMax", _fmt(max(r["minimum_chi2"] for r in audit["rows"])))
        mac("auditBallCut", _fmt(audit["rows"][0]["gaussian_ball_cutoff"]))

    cycle = _latest("phase_cycle_validation.json")
    if cycle:
        mac("cycleResetError", _fmt(cycle["max_reset_equivalence_error"]))
        mac("cycleFormulaError", _fmt(cycle["max_closed_form_error"]))
        mac("cycleTwirlError", _fmt(cycle["max_enumerated_twirl_error"]))
        mac("cycleBlocks", str(cycle["blocks"]))
        mac("cycleTrials", str(cycle["calibration"][0]["trials"]))
        mac("cycleTruth", _fmt(cycle["calibration"][0]["truth"], 4))
        for row in cycle["calibration"]:
            name=row["control"].title()
            mac(f"cycle{name}Detect", _fmt(100*row["detection_rate"],1))
            mac(f"cycle{name}Coverage", _fmt(100*row["bootstrap_coverage"],1))
            mac(f"cycle{name}Finite", _fmt(100*row["finite_sample_coverage"],1))

    cycle_hardware = sorted(DATA.glob("phase_cycle_*_results.json"))
    mac("cycleHardwareRuns", str(len(cycle_hardware)))
    for label, path in zip(("First", "Second"), cycle_hardware):
        result = json.loads(path.read_text(encoding="utf-8"))
        primary = result["primary"]
        mac(f"cycle{label}Primary", _fmt(primary["estimate"], 3))
        mac(f"cycle{label}Lo", _fmt(primary["ci"][0], 3))
        mac(f"cycle{label}Hi", _fmt(primary["ci"][1], 3))

    survey = _latest("survey_*_survey_results.json")
    if survey:
        mac("surveyN", str(len(survey)))
        mac("surveyAllMemoryless",
            "all" if all(r["label"] == "memoryless" for r in survey) else "not all")

    off = _latest("survey_*_offset_results.json")
    if off:
        vals = [r["nu_offset"] for r in off if r.get("nu_offset")]
        if vals:
            mac("surveyNuMin", _fmt(min(vals)))
            mac("surveyNuMax", _fmt(max(vals)))

    conf = _latest("survey_ibm_fez_*_confirm_results.json")
    if conf:
        w = [r["w_var_rep"] for r in conf if r.get("w_var_rep") is not None]
        if w:
            mac("confirmWvarMin", _fmt(min(w)))
            mac("confirmWvarMax", _fmt(max(w)))

    # ---- Second device: replication of the null, and its own screen/confirm pair -------
    m_surv = _latest("survey_ibm_marrakesh_*_survey_results.json")
    if m_surv:
        mac("devTwo", "ibm\\_marrakesh")
        mac("devTwoN", str(len(m_surv)))
        vals = [(r["nu_offset"], r.get("nu_offset_err") or 0.0, r["qubit"])
                for r in m_surv if r.get("nu_offset") is not None]
        if vals:
            top = max(vals)
            mac("devTwoTopQubit", str(top[2]))
            mac("devTwoTopNu", _fmt(top[0]))
            mac("devTwoTopErr", _fmt(top[1]))
            mac("devTwoTopLo", _fmt(top[0] - 2 * top[1]))
    m_conf = _latest("survey_ibm_marrakesh_*_confirm_results.json")
    if m_conf:
        r = m_conf[0]
        mac("devTwoConfNu", _fmt(r["nu_offset"]))
        mac("devTwoConfErr", _fmt(r.get("nu_offset_err") or 0.0))
        mac("devTwoConfLo", _fmt(r["nu_offset"] - 2 * (r.get("nu_offset_err") or 0.0)))
        if r.get("w_var_rep") is not None:
            mac("devTwoConfWvar", _fmt(r["w_var_rep"]))
    # Total qubits screened across both devices.
    n_total = len(_latest("survey_ibm_fez_*_survey_results.json") or []) + len(m_surv or [])
    if n_total:
        mac("totalQubits", str(n_total))

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines) - 3} macros)")
    _check_manuscript_macros(lines)


def _check_manuscript_macros(lines):
    """Fail loudly if the manuscript cites a macro this run did not generate.

    Without LaTeX installed there is no compile step to catch it, and an undefined macro is
    exactly the kind of error that surfaces as a blank or a raw command name in a submitted
    PDF. Checking here means a missing data file is reported as a missing NUMBER, naming the
    sentence that would have been wrong.
    """
    import re

    tex = Path("paper") / "main.tex"
    if not tex.exists():
        return
    defined = set(re.findall(r"\\newcommand\{\\(\w+)\}", "\n".join(lines)))
    # Macros defined inline in the manuscript preamble are fine too.
    body = tex.read_text(encoding="utf-8")
    defined |= set(re.findall(r"\\newcommand\{\\(\w+)\}", body))
    used = set(re.findall(r"\\([A-Za-z]+)\{?\}?", body))
    known_latex = set("""documentclass usepackage input newcommand begin end title author
        affiliation date maketitle abstract section subsection label ref cite bibliography
        bibliographystyle includegraphics caption figure table textbf emph item enumerate
        colrule ruledtabular tabular acknowledgments frac mathrm text left right qquad quad
        SI percent dd tc nu delta sigma tau phi theta epsilon varepsilon approx lesssim ll gg
        ge le pm times cdots ldots mathcal mathbb equation align gather notag nonumber
        columnwidth linewidth hline toprule midrule bottomrule url href texttt xspace
        ASF EPC Wvar Wrep sqrt int sum exp ln log to infty rightarrow leftarrow
        graphicspath centering vspace hspace par noindent footnote textwidth
        """.split())
    missing = sorted(m for m in used - defined - known_latex
                     if re.match(r"^[a-z][A-Za-z]*$", m) and any(c.isupper() for c in m))
    if missing:
        print("\n  !! manuscript uses macros that were NOT generated:")
        for m in missing:
            ctx = [ln.strip() for ln in body.splitlines() if "\\" + m in ln]
            print(f"     \\{m}   e.g. {ctx[0][:90] if ctx else ''}")
        print("     (usually means the corresponding data/*.json is absent)")
    else:
        print("  all manuscript macros resolved")


if __name__ == "__main__":
    main()
